config/routes.rb
Rails.application.routes.draw do
  get 'users/toggle_proxy'

  root 'pages#index'
  get 'faq', to: 'pages#faq', as: :faq
  get 'search', to: 'pages#search', as: :search
  get 'toggle_proxy', to: 'pages#toggle_proxy', as: :toggle_proxy

  resources :products, only: [:index, :show, :destroy]

  %w(actresses codes genres makers titles).each do |endpoint|
    get "api/#{endpoint}"
  end
end

app/models/product.rb
class Product < ActiveRecord::Base
  #=============
  # Validations
  #=============
  validates :code, :title, :cover_image, presence: true
  validates :code, uniqueness: true

  #========
  # Search
  #========
  def self.search(query)
    find_by_code(query) || search_using_opendmm(query)
  end

  def self.search_using_opendmm(query)
    details = OpenDMM.search(query)
    return nil unless details
    product = find_by_code(details[:code]) || create(details)
    product.save ? product : nil
  end

  #=======
  # Other
  #=======
  def thumbnail_image
    super || self.cover_image
  end

  def refresh!
    return false if updated_at >= 10.minute.ago
    details = OpenDMM.search(code)
    return false unless details
    self.attributes = details
    return false unless changed?
    save
  end

  def to_param
    code
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception
  add_flash_types :success, :info, :warning, :danger
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def search
    query = params[:q]
    if query.blank?
      redirect_to root_url
    elsif product = Product.search(query)
      redirect_to product
    else
      render 'products/not_found'
    end
  end

  def toggle_proxy
    if cookies[:use_image_proxy]
      cookies.delete :use_image_proxy
    else
      cookies.permanent[:use_image_proxy] = true
    end
    redirect_to :back
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :destroy]

  def show
    if @product
      respond_to do |format|
        format.html
        format.json { render json: @product, except: [:id, :created_at, :updated_at] }
      end
    else
      render :notfound, status: :not_found
    end
  end

  def destroy
    if @product.refresh!
      redirect_to @product, info: "Product information refreshed, if you still believe it's wrong, click Report Error again. Thanks!"
    else
      logger.tagged 'ERROR_REPORT' do logger.error params[:id] end
      redirect_to @product, success: "Error reported. Thanks!"
    end
  end

  private
    def set_product
      @product = Product.search(params[:id])
      logger.tagged 'NOT_FOUND' do logger.warn params[:id] end unless @product
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def proxy_image(image_url)
    force_proxy_hosts = [ "rsc.aurora-pro.com" ]
    if URI(image_url).host.in?(force_proxy_hosts) || use_image_proxy?
      image_url.gsub!(/^http:\/\//, 'http://proxy.libredmm.com/')
    end
    image_url
  end

  def use_image_proxy?
    cookies[:use_image_proxy]
  end
end

app/helpers/bootstrap_helper.rb
module BootstrapHelper
  def icon_fa(icon, text='')
    icon_tag = content_tag(:i, nil, class: "fa fa-fw fa-#{icon}").html_safe
    text.blank? ? icon_tag : icon_tag + ' ' + text
  end

  def bootstrap_class_for_flash(name)
    case name
    when 'notice'
      'success'
    when 'alert'
      'danger'
    else
      name
    end
  end
end

app/helpers/products_helper.rb
module ProductsHelper
  def image_link_to(image, link_options = {}, image_options = {})
    image_options.reverse_merge!(ref: 'noreferer')
    link_to image, link_options do
      image_tag image, image_options
    end
  end

  def product_spec(term, description = nil, icon = nil, &block)
    return nil if description.blank?
    case description
    when Array
      description = content_tag(:ul, class: 'list-unstyled') do
        description.map do |item|
          content_tag(:li) do
            icon_fa(icon, item)
          end
        end.join.html_safe
      end
    else
      description = icon_fa(icon, description)
    end
    (content_tag(:dt, term) + content_tag(:dd, description)).html_safe
  end
end

app/views/layouts/_analytics.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-52585423-1', 'auto');
  ga('require', 'displayfeatures');
  ga('require', 'linkid', 'linkid.js');
  ga('send', 'pageview');
</script>

app/views/layouts/_flash.html.erb
<div class='flash'>
  <% flash.each do |name, msg| %>
    <div class='alert alert-<%= bootstrap_class_for_flash(name) %>'>
      <button type='button' class='close' data-dismiss='alert' aria-hidden='true'>&times;</button>
      <%= content_tag :div, raw(msg) %>
    </div>
  <% end %>
</div>

app/views/layouts/_footer.html.erb
<footer>
  <div class='container'>
    <span>Copyright © since 2014 LibreDMM All Rights Reserved</span>
    ·
    <a href='mailto: admin@libredmm.com'>
      <%= icon_fa 'envelope-o', 'Contact Admin' %>
    </a>
  </div>
</footer>

app/views/layouts/_navbar.html.erb
<nav class='navbar navbar-default navbar-fixed-top' role='navigation'>
  <div class='container-fluid'>
    <div class='navbar-header'>
      <button type='button' class='navbar-toggle' data-toggle='collapse' data-target='#navbar-top'>
        <span class='sr-only'>Toggle navigation</span>
        <span class='icon-bar'></span>
        <span class='icon-bar'></span>
        <span class='icon-bar'></span>
      </button>
      <a class='logo navbar-brand' href='/'>LibreDMM</a>
    </div>
    <div class='collapse navbar-collapse' id='navbar-top'>
      <% unless request.url == root_url %>
        <%= form_tag search_path, method: :get, class: 'navbar-form navbar-left' do %>
          <div class='form-group'>
            <%= text_field_tag 'q', nil, class: 'form-control input-sm'%>
          </div>
          <%= submit_tag 'Search', class: 'btn btn-success btn-sm' %>
        <% end %>
      <% end %>
      <ul class='nav navbar-nav navbar-right'>
        <%= yield :navbar_links %>
        <li class='has-tooltip' data-toggle='tooltip' data-placement='bottom' title="Can't see image? Try turning proxy on.">
          <%= link_to toggle_proxy_path do %>
            <%= icon_fa 'magic', 'Proxy ' %>
            <% if use_image_proxy? %>
              ON
            <% else %>
              OFF
            <% end %>
          <% end %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html ng-app='libredmm'>
<head>
  <title>
    <% if content_for? :title %>
      <%= yield :title %> |
    <% end %>
    LibreDMM
  </title>
  <%= stylesheet_link_tag    'application', 'data-turbolinks-track' => true, media: 'all' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/navbar' %>
  <div class='container'>
    <%= render 'layouts/flash' %>
    <%= yield %>
  </div>
  <%= render 'layouts/footer' %>
  <%= render 'layouts/analytics' %>
</body>
</html>

app/views/pages/index.html.erb
<article class='index row'>
  <div class='col-sm-8 col-sm-offset-2'>
    <p class='logo logo-lg'>LibreDMM</p>
    <%= form_tag search_path, method: :get, class: 'form' do %>
      <div class='form-group'>
        <%= text_field_tag( 'q', nil, class: 'form-control') %>
      </div>
      <div class='form-group'>
        <%= submit_tag 'Search', class: 'btn btn-success' %>
      </div>
    <% end %>
  </div>
</article>

app/views/products/notfound.html.erb
<article class='jumbotron'>
  <p>Sorry, we could not find product <strong><%= params[:id] %></strong></p>
</article>

app/views/products/show.html.erb
<% content_for :title do %>
  <%= @product.code %> <%= @product.title %>
<% end %>

<article class='product product-show row'>
  <header class='col-sm-12'>
    <h1>
      <span><%= yield :title %></span>
      <small><%= @product.subtitle %></small>
    </h1>
  </header>
  <section class='cover col-sm-8'>
    <%= image_link_to proxy_image(@product.cover_image), {}, class: 'img-rounded' %>
  </section>
  <section class='details col-sm-4'>
    <dl class='dl-horizontal'>
      <%= product_spec('Actresses', @product.actresses, 'female') %>
      <%= product_spec('Directors', @product.directors, 'male') %>

      <%= product_spec('Actress Types', @product.actress_types, 'tags') %>
      <%= product_spec('Boobs', @product.boobs, 'dot-circle-o') %>
      <%= product_spec('Brand', @product.brand, 'tag') %>
      <%= product_spec('Categories', @product.categories, 'folder-o') %>
      <%= product_spec('Genres', @product.genres, 'tags') %>
      <%= product_spec('Label', @product.label, 'tag') %>
      <%= product_spec('Scatologies', @product.scatologies, 'tags') %>
      <%= product_spec('Scenes', @product.scenes, 'tags') %>
      <%= product_spec('Series', @product.series, 'folder') %>
      <%= product_spec('Tags', @product.tags, 'tags') %>
      <%= product_spec('Transsexualities', @product.transsexualities, 'tags') %>
      <%= product_spec('Theme', @product.theme, 'tag') %>

      <%= product_spec('Movie Length',
                       distance_of_time(@product.movie_length), 'clock-o'
                      ) if @product.movie_length %>
      <%= product_spec('Release Date', @product.release_date, 'calendar') %>

      <%= product_spec('Maker', @product.maker, 'suitcase') %>
      <%= product_spec('Source Page',
                       link_to(URI(@product.page).host, @product.page, target: '_blank'),
                       'suitcase') %>
    </dl>
    <dl class='dl-horizontal'>
      <dt></dt>
      <dd>
        <%= link_to product_path(@product), class: 'btn btn-warning btn-sm', method: :delete do %>
          <%= icon_fa 'paper-plane', 'Report Error' %>
        <% end %>
      </dd>
    </dl>
  </section>
  <% if @product.description.present? %>
    <section class='description col-sm-12'>
      <h2>Description</h2>
      <p><%= @product.description %></p>
    </section>
  <% end %>
  <% if @product.sample_images.present? %>
    <section class='samples col-sm-12'>
      <h2>Sample Images</h2>
      <%- @product.sample_images.in_groups_of(6, false).each do |group| %>
        <div class='sample-group col-sm-12 row'>
          <%- group.each do |image| %>
            <%= image_link_to proxy_image(image), class: 'thumbnail col-sm-2' %>
          <%- end %>
        </div>
      <%- end %>
    </section>
  <% end %>
</article>